version: "3"

services: 
  db: 
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres
  backend: 
    build: ./backend
    command: >
        sh -c "python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
    ports: 
      - "8000:8000"
    volumes: 
      - ./backend:/app/backend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend:/app/frontend
    command: npm start
    stdin_open: true